#!/bin/bash

echo -e "\n#\n#\n#\n#\n#\n#\n#\n#\n#\n###LOCALE###\n#\n#\n#\n#\n#\n#\n#\n#\n#\n"

sleep 1

mv /etc/locale.gen /etc/locale.gen.bak

echo -e 'pt_BR.UTF-8 UTF-8' | tee /etc/locale.gen

locale-gen

echo -e 'LANG=pt_BR.UTF-8' | tee /etc/locale.conf

pacman -S xdg-user-dirs --noconfirm

xdg-user-dirs-update
